name: 'SnowFlakeDBTTEST'
version: '1.0'
config-version: 2

profile: 'SnowFlakeDBTTEST'

models:
  SnowFlakeDBTTEST:
    snowflaketest:
      200_Filter:
        +database: SNOWFLAKE_LEARNING_DB
        +schema: MY_NEW_SCHEMA