name: 'SnowFlakeDBTTEST'
version: '1.0'
config-version: 2

profile: 'SnowFlakeDBTTEST'

models:
  SnowFlakeDBTTEST:
    snowflaketest:
      200_Filter:
        +schema: INFORMATION_SCHEMA   # 👈 This is the user-defined schema name